version: '3.7'
services:

  web:
    image: registry.gitlab.com/tochka-masters/ohooho/web:dev
    build:
      context: .
      dockerfile: Dockerfile.web
      labels:
        VERSION: "${VERSION:-unknown}"

  worker:
    image: registry.gitlab.com/tochka-masters/ohooho/worker:dev
    build:
      context: .
      dockerfile: Dockerfile.worker
      labels:
        VERSION: "${VERSION:-unknown}"
