# Generated by Django 2.2.9 on 2020-01-04 11:50
import datetime
import uuid

# import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models

try:
    from django.db.models import JSONField
    postgres_only = False
except ImportError:
    from django.contrib.postgres.fields import JSONField
    postgres_only = True


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ext_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('C', 'Выставлен'), ('U', 'Отменен'), ('W', 'Подтвержден'), ('P', 'Не принят (код протекции)'), ('E', 'Не принят (не верная сумма)'), ('V', 'Оплачен')], default='C', max_length=1)),
                ('sid', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('event', models.CharField(editable=False, max_length=100)),
                ('check_amount', models.BooleanField(default=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=64, null=True)),
                ('comment', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sys_code', models.CharField(default='default_code', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=64)),
                ('parameter', models.PositiveIntegerField(blank=True, null=True)),
                ('trial_period', models.PositiveIntegerField(blank=True, null=True)),
                ('trial_unit', models.CharField(choices=[(None, 'No recurrence'), ('0', 'No trial'), ('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], default='M', max_length=1, null=True)),
                ('recurrence_period', models.PositiveIntegerField(blank=True, null=True)),
                ('recurrence_unit', models.CharField(choices=[(None, 'No recurrence'), ('0', 'No trial'), ('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], default='M', max_length=1, null=True)),
                ('available_until', models.DateField(default=datetime.date(9999, 12, 31), null=True)),
                ('available_from', models.DateField(default=datetime.date.today, null=True)),
                ('active', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('items', JSONField(default=dict)), #django.contrib.postgres.fields.JSONField 
                ('expires_date', models.DateField(blank=True, default=None, null=True)),
                ('activate_date', models.DateField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('period_count', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('period_unit', models.CharField(choices=[(None, 'No recurrence'), ('0', 'No trial'), ('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], default='M', max_length=1, null=True)),
                ('invoice', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs_history', to='billing.Invoice')),
                ('subscription', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs_history', to='billing.Subscription')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=64, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('addressee', models.EmailField(blank=True, max_length=254, null=True, verbose_name='addressee')),
                ('code', models.CharField(max_length=30)),
                ('available_from', models.DateTimeField(default=datetime.datetime.now)),
                ('available_until', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
                ('subscription', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Subscription')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Subscription'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('index', models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=2, null=True)),
                ('withdraw_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=64, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=64, null=True)),
                ('fact_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения оплаты')),
                ('notification_type', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('unaccepted', models.NullBooleanField(default=False)),
                ('code_pro', models.NullBooleanField(default=False)),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('operation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='billing.Invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
