# Generated by Django 2.2.9 on 2020-01-04 13:43
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('N', 'Выставлен'), ('U', 'Отменен'), ('W', 'Подтвержден'), ('P', 'Не принят (код протекции)'), ('E', 'Не принят (не верная сумма)'), ('V', 'Оплачен')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Subscription'),
        ),
    ]
