# Generated by Django 2.2.11 on 2020-03-14 13:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscriptionhistory_fix_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
