# Generated by Django 2.2.7 on 2019-11-25 07:09
import core.models
# import django.contrib.postgres.fields.jsonb
import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('DEF', 'default'), ('VK', 'VK')], default='DEF', max_length=5, null=True)),
                ('src_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField(max_length=1000)),
                ('count', models.IntegerField(default=0)),
                ('cover', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='media/', location='/Users/kulikovaleksandr/projects/research/ohooho/app/media'), upload_to=core.models.user_album_path)),
                ('last_update_photos', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_search_photos', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('WORK', 'В работе'), ('UPD', 'Обновляется'), ('DONE', 'Готово')], default='NEW', max_length=4, verbose_name='Статус обработки')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_name', models.CharField(blank=True, default='', max_length=1000)),
                ('version', models.CharField(blank=True, default='v0.1', max_length=10)),
                ('score', core.models.NumpyFloatField(blank=True, null=True)),
                ('confusion_matrix', models.CharField(blank=True, default='', max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DomainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('DEF', 'default'), ('VK', 'VK')], default='DEF', max_length=5, null=True)),
                ('src_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('search_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('domain', models.URLField(default='', max_length=1000)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domaindata', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('DEF', 'default'), ('VK', 'VK')], default='DEF', max_length=5, null=True)),
                ('src_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mini_url', models.URLField(blank=True, default=None, max_length=1000, null=True)),
                ('maxi_url', models.URLField(blank=True, default=None, max_length=1000, null=True)),
                ('source_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('source_album', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('source_owner', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('search_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('labels', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('tags', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('similar_data', models.BinaryField(blank=True, default=None, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Album')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='media/', location='/Users/kulikovaleksandr/projects/research/ohooho/app/media'), upload_to=core.models.user_profile_path)),
                ('birthday', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('hometown', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='join date')),
                ('join_location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('anonym_session_key', models.CharField(blank=True, default='', max_length=100)),
                ('total_photos', models.IntegerField(default=0)),
                ('user_agent', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=200, null=True)),
                ('utm_referrer', models.CharField(blank=True, max_length=100, null=True)),
                ('show_nps', models.IntegerField(choices=[(10, 'Sleep'), (11, 'Wait'), (12, 'Trigger'), (13, 'Fire'), (14, 'Done')], default=10)),
                ('show_welcome', models.IntegerField(choices=[(10, 'Sleep'), (11, 'Wait'), (12, 'Trigger'), (13, 'Fire'), (14, 'Done')], default=10)),
                ('last_visit', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nps', models.IntegerField(default=0)),
                ('answer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(blank=True, default='', max_length=10000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_nps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('DEF', 'default'), ('VK', 'VK')], default='DEF', max_length=5, null=True)),
                ('src_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('engine', models.IntegerField(choices=[(10, 'Yandex cloud'), (15, 'Yandex'), (30, 'Google cloud'), (35, 'Google'), (20, 'Bing'), (40, 'TinEye'), (50, 'Vk api')], default=15)),
                ('page_url', models.URLField(max_length=1000)),
                ('title', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('image_url', models.URLField(max_length=1000)),
                ('favicon_url', models.URLField(blank=True, default='', max_length=1000, null=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_checked', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_modified', models.DateTimeField(blank=True, default=None, null=True)),
                ('partial_matching', models.BooleanField(default=False)),
                ('similar_images', models.BooleanField(default=False)),
                ('views_number', models.IntegerField(default=0)),
                ('views_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('found_image', models.BooleanField(default=False)),
                ('mention_exact_match', models.BooleanField(default=False)),
                ('mention_similar', models.BooleanField(default=False)),
                ('similar_data', models.JSONField(default=dict)), #django.contrib.postgres.fields.jsonb.JSONField
                ('predict_similar', models.BooleanField(blank=True, default=None, null=True)),
                ('verified_similarity', models.BooleanField(blank=True, default=None, null=True)),
                ('verified_skip', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainData')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='core.Photo', verbose_name='photo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='searchresult', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngineCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateField(blank=True, default=None, null=True)),
                ('engine', models.CharField(choices=[('IMAGE', 'Image search engine'), ('VIEWS', 'Views counter'), ('EMAIL', 'Email finding')], default='IMAGE', max_length=10)),
                ('name', models.CharField(default='None', max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('album', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Album')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enginecounter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DomainContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('DEF', 'default'), ('VK', 'VK')], default='DEF', max_length=5, null=True)),
                ('src_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('search_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('engine', models.IntegerField(choices=[(10, 'Hunter'), (15, 'Lusha'), (20, 'Hiretool'), (30, 'Find That Email'), (35, 'Google'), (40, 'Yandex')], default=10)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainData')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domaincontacts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('DEF', 'default'), ('VK', 'VK')], default='DEF', max_length=5, null=True)),
                ('src_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('vk_profile', models.URLField(blank=True, max_length=1000, null=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='core.Author'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
