# Generated by Django 2.2.9 on 2020-01-04 16:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
