# Generated by Django 2.2.11 on 2020-03-14 12:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200314_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='search_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
