# Generated by Django 2.2.11 on 2020-03-14 15:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_photo_search_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginecounter',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
