# Generated by Django 2.2.11 on 2020-03-15 07:59
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_enginecounter_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='founders_access',
            field=models.BooleanField(default=False),
        ),
    ]
