# Generated by Django 2.2.11 on 2020-03-15 15:46
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_founders_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='anonym_session_key',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
