# Generated by Django 2.2.11 on 2020-03-15 19:50
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200315_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginecounter',
            name='photo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Photo'),
        ),
    ]
