# Generated by Django 2.2.11 on 2020-03-15 20:03
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_enginecounter_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
    ]
