# Generated by Django 2.2.11 on 2020-04-19 10:22
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_enginecounter_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='crawl_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
