# Generated by Django 2.2.11 on 2020-04-27 17:59
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_author_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
